---
- name: prepare container for test
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create container mysql57
      docker_container:
        name: mysql57
        image: hxpro/docker-centos
#        recreate: yes
        privileged: true
        command: /usr/sbin/init
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
        state: started

    - name: add mysql57 host
      add_host: name=mysql57 groups=containers

- name: provision role
  hosts: containers
  connection: docker
  vars:
    mysql_vars:
      max_allowed_packet: 128M
      server_id: 1
      skip-name-resolve:
  roles:
    - role: "{{ playbook_dir }}"


#- name: tear down
#  hosts: localhost
#  gather_facts: no
#  connection: local
#
#  tasks:
#    - name: Destroy containers
#      docker_container:
#        name: '{{ item }}'
#        state: absent
#      with_items:
#        - mysql57
