---
- name: Configure mysqld section in my.cnf
  ini_file:
    dest: /etc/my.cnf
    section: mysqld
    option: "{{ item }}"
    value: "{{ lookup('vars', 'mysql_' + item) }}"
    create: False
  with_items: "{{ mysql_mysqld_vars }}"
  when: vars['mysql_' + item ] is defined
  notify: restart mysqld
  register: mycnf

- name: Configure client section in my.cnf
  ini_file:
    dest: /etc/my.cnf
    section: client
    option: "{{ item }}"
    value: "{{ lookup('vars', 'mysql_' + item) }}"
    create: False
  with_items: "{{ mysql_client_vars }}"
  when: vars['mysql_' + item ] is defined

- name: Create mysql datadir
  file:
    path: "{{ mysql_datadir }}"
    mode: '0750'
    owner: 'mysql'
    group: 'mysql'
    state: directory

- name: Create mysql tmpdir
  file:
    path: "{{ mysql_tmpdir }}"
    mode: '0755'
    owner: 'mysql'
    group: 'mysql'
    state: directory
  when: mysql_tmpdir is defined

- name: Set selinux context on datadir
  sefcontext:
    target: "{{ mysql_datadir }}(/.*)?"
    setype: mysqld_db_t
    state: present
  when: selinux|bool

- name: Set selinux context on tmpdir if is defined
  sefcontext:
    target: "{{ mysql_tmpdir }}(/.*)?"
    setype: mysqld_db_t
    state: present
  when: mysql_tmpdir is defined and selinux|bool

- name: Apply new SELinux file context to datadir
  command:
    cmd: "restorecon -irv {{ mysql_datadir }}"
  when: selinux|bool

- name: Apply new SELinux file context to tmpdir
  command: "restorecon -irv {{ mysql_tmpdir }}"
  when: mysql_tmpdir is defined and selinux|bool

- name: Initialize datadir
  command:
    cmd: mysqld --initialize-insecure --user=mysql
    creates: "{{ mysql_datadir }}/auto.cnf"

- name: Verify configuration
  shell: mysqld --verbose --help 1>/dev/null

- name: Start/enable mysql daemon
  service:
    name: mysqld
    state: started
    enabled: yes
