---
- name: Install mysql57-community-release
  package: name='https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm' state=installed

- name: Install mysql packages
  package: name={{ mysql_pkg }} state=installed

- name: Configure my.cnf
  ini_file:
    dest: /etc/my.cnf
    section: mysqld
    option: "{{ item }}"
    value: "{{ mysql_vars[item] }}"
    allow_no_value: yes
    backup: yes
  with_items: "{{ mysql_vars }}"
  notify: restart mysqld

- name: Verify configuration
  shell: mysqld --verbose --help 1>/dev/null

- name: Initialize datadir
  command: mysqld --initialize-insecure --user=mysql
    creates="{{ mysql_vars['datadir'] | default('/var/lib/mysql') }}/auto.cnf"

- name: Start/enable mysql daemon
  service: name=mysqld state=started enabled=yes
