---
- name: Install mysql57-community-release
  package: name='https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm' state=installed

- name: Install mysql packages
  package: name={{ mysql_pkg }} state=installed

- name: Configure datadir
  ini_file:
    dest=/etc/my.cnf
    section=mysqld
    option=datadir
    value="{{ mysql_datadir }}"
  notify: restart mysqld

- name: Configure max allowed packet
  ini_file:
    dest=/etc/my.cnf
    section=mysqld
    option=max_allowed_packet
    value="{{ mysql_max_allowed_packet }}"
  when: mysql_max_allowed_packet is defined
  notify: restart mysqld

- name: Server-id
  ini_file:
    dest=/etc/my.cnf
    section=mysqld
    option=server-id
    value="{{ mysql_server_id | int }}"
  when: mysql_server_id is defined
  notify: restart mysqld

- name: Initialize datadir
  command: mysqld --initialize-insecure --user=mysql
    creates="{{ mysql_datadir }}/auto.cnf"

- name: Start/enable mysql daemon
  service: name=mysqld state=started enabled=yes
