---
- name: Include platform specific vars
  include_vars: "{{ lookup('first_found', vars_files) }}"
  vars:
    vars_files:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "generic.yml"
      paths:
        - "vars"

- name: Disable default mysql module
  copy:
    dest: /etc/dnf/modules.d/mysql.module
    content: |
      [mysql]
      name=mysql
      stream=
      profiles=
      state=disabled
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8

- name: Add rpm gpg key
  rpm_key:
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Download mysql-community-release
  get_url:
    url: "{{ mysql_release_url }}"
    dest: "/usr/local/src/"
    checksum: "{{ mysql_release_checksum }}"
  register: _release_rpm_file

- name: Debug
  debug:
    var: _release_rpm_file

- name: Install mysql-community-release
  package:
    name: "{{ _release_rpm_file.dest }}"
    state: present

- name: Install mysql packages
  package:
    name: "{{ mysql_pkg }}"
    state: present
